### ISSUE TITLE
sqlite3 as peer dependency to allow custom binaries

### ISSUE THREAD

**Issue by theDevelopper** [kriasoft/node-sqlite#60] opened 2018-05-11 15:14 UTC
Hi, 

as sqlite3 is a binary module I would like to propose to make sqlite3 a peer dependency rather than a dependency. 
The reason for this is, that not all combination of runtime environments, architectures and such are available as binaries and there are cases where a manual build from source is necessary. For example with nwjs. 
When installed as a peer dependency we would have full control over version and binary (if properly defined in the package.json) and we could easily run the `npm install sqlite3 --build-from-source ...` command.
This would also allow other packages to use the same sqlite3 version, rather than having separate version, if these package also require it as a peer.

Cheers

**Comment by theogravity** [comment] 2018-05-14 20:12
This sounds like a dupe of https://github.com/kriasoft/node-sqlite/issues/59

**Closed** 2018-05-15 08:50 UTC
Labels: duplicate
